### ISSUE TITLE
Belgium / Vlaanderen

### ISSUE THREAD

**Issue by skinkie** [TOMP-WG/TOMP-API#151] opened 2020-05-06 07:03 UTC
The current standard in Belgium;

Mobiliteit: Trips & Aanbod (Applicatieprofiel)
https://data.vlaanderen.be/doc/applicatieprofiel/mobiliteit-trips-en-aanbod

**Comment by Tjalle** [comment] 2020-05-13 08:01
Ah, they've taken it out of test. Thnx for sharing.

**Comment by pimmeh** [comment] 2020-05-13 09:40
Thanks for the information. This is not a bug or feature request so I'm going to close this issue. Further discussion can be done in slack.

**Closed by pimmeh** 2020-05-13 09:40 UTC
