### ISSUE TITLE
New API-call: subscribe to asset updates

### ISSUE THREAD

**Issue by pimmeh** [TOMP-WG/TOMP-API#39] opened 2019-07-01 13:06 UTC
After the last TOMP-meeting, we figured out that if the end user is reviewing a trip suggestion made by the MaaS-provider with all the suggested assets that should be booked, the status of those assets can change. In order to not dissapoint an end user (for instance, that an asset is no longer available while the end user reviews the suggested journey before actually booking it), the MaaS Provider can request updates to an asset from the Transport Operator.

These updates enable the MaaS provider to inform the end user when the showed journey is no longer valid because the requested asset is no longer available.

I see two versions of how we can do this.

### Subscribe / unsubscribe
Using POST/subscribe/{asset-id} and DELETE/subscribe/{asset-id} we can tell the transport operator to send us updats about the asset. The advantage here is that we use a subscription model and polling is not neccessary. The disadvantage is that we need an endpoint on the MaaS provider side where the updates can be sent using, for instance, POST/asset-update/{asset-id}.

### Polling
We can use GET/statusupdate/{asset-it} from MaaS provider to transport operator to periodically ask for an update on each asset. The advantage here is that it doesn't require another endpoint at the MaaS provider side. The disadvantage is that lag behind the truth and it generates more traffic and load.

What are your thoughts?

**Comment by edwinvandenbelt** [comment] 2019-07-09 10:45
Maybe another alternative: listen to a bus (like Bison)

**Comment by ro5k0** [comment] 2019-07-09 10:49
I think this is part of a larger discussion here 
Duplicate of #12

**Comment by edwinvandenbelt** [comment] 2019-07-09 11:10
Correct, but this issue is about the technique, not the functionality (#12)

**Comment by ro5k0** [comment] 2019-07-09 11:12
Ok fair point but I thought we discussed not doing polling in a previous meeting for the very reasons that @pimmeh outlines above.If I'm mistaken then I would say that we don't really want to do polling for the reasons above.

**Comment by ro5k0** [comment] 2019-07-09 11:15
#12 expands on how we should handle subscribe/unsubscribe and at what stage so it would be good to keep further discussions about that in the other issue.

**Comment by edwinvandenbelt** [comment] 2019-09-05 12:13
I think this way of working is the simplest one: 
1) check availability: the TO can send asset-types and optionally an asset. The TO should keep track of which MSP requested it. 
2) in case of unavailability the TO can send a 'availability-expired'. This can be done on asset-type or asset (it expires the availability-id),
3) this can also be done after the 'availablity-request'
See: https://github.com/efel85/TOMP-API/issues/9

**Comment by edwinvandenbelt** [comment] 2019-09-27 09:29
In case the asset isn't available anymore (e.g. temporary broken) the TO can send a notification message to inform (the user, but that's up to the MSP) and optionally assign a new asset to the trip (if needed) by using a endpoint that's not yet foreseen. Should it be in the booking phase or in the trip execution phase? suggestion: PATCH /trip/{id}}/assign-asset with a proper json body.

**Comment by edwinvandenbelt** [comment] 2019-12-06 08:37
I think this can be done now using the 'subscribe' endpoint...

**Closed** 2020-05-20 07:44 UTC
Labels: WT1, change request
