### ISSUE TITLE
[FEATURE REQUEST] Allow POST /booking to respond with 410 Gone

### ISSUE THREAD

**Issue by piotrj** [TOMP-WG/TOMP-API#301] opened 2020-11-17 10:15 UTC
## Is your feature request related to a problem? Please describe.
When someone tries to create a booking with an id that is not valid anymore (the `validUntil` provided in plannings response passed or something else happened) then it would be nice to have that clear with proper status code. 

## Urgency
Minor

## Describe the solution you'd like
410 as possible http response

## Describe alternatives you've considered
We could use 404 for this. But 410 is more explicit.

**Comment by edwinvandenbelt** [comment] 2020-11-17 14:30
Is this a duplicate of #264 ?

**Comment by piotrj** [comment] 2020-11-17 15:49
@edwinvandenbelt not necesarilly. `409` would mean that you got that booking secured and you are just duplicating the call. `410` would mean that the booking prepared for you is not available anymore - for example the `validUntil` for booking passed and in the meantime someone already booked the last bike from the station you wanted or bought the last ticket for this train ride.

**Closed** 2020-12-01 13:35 UTC
Labels: WT1
